//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteSOAP.CotizacionServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CotizacionServiceClient.CotizacionServiceSoap")]
    public interface CotizacionServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        ClienteSOAP.CotizacionServiceClient.obtenerCotizacionResponse obtenerCotizacion(ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSOAP.CotizacionServiceClient.obtenerCotizacionResponse> obtenerCotizacionAsync(ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        ClienteSOAP.CotizacionServiceClient.registrarCotizacionResponse registrarCotizacion(ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteSOAP.CotizacionServiceClient.registrarCotizacionResponse> registrarCotizacionAsync(ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequestBody Body;
        
        public obtenerCotizacionRequest() {
        }
        
        public obtenerCotizacionRequest(ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public obtenerCotizacionRequestBody() {
        }
        
        public obtenerCotizacionRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSOAP.CotizacionServiceClient.obtenerCotizacionResponseBody Body;
        
        public obtenerCotizacionResponse() {
        }
        
        public obtenerCotizacionResponse(ClienteSOAP.CotizacionServiceClient.obtenerCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerCotizacionResult;
        
        public obtenerCotizacionResponseBody() {
        }
        
        public obtenerCotizacionResponseBody(string obtenerCotizacionResult) {
            this.obtenerCotizacionResult = obtenerCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequestBody Body;
        
        public registrarCotizacionRequest() {
        }
        
        public registrarCotizacionRequest(ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto;
        
        public registrarCotizacionRequestBody() {
        }
        
        public registrarCotizacionRequestBody(string fecha, decimal monto) {
            this.fecha = fecha;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteSOAP.CotizacionServiceClient.registrarCotizacionResponseBody Body;
        
        public registrarCotizacionResponse() {
        }
        
        public registrarCotizacionResponse(ClienteSOAP.CotizacionServiceClient.registrarCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarCotizacionResult;
        
        public registrarCotizacionResponseBody() {
        }
        
        public registrarCotizacionResponseBody(string registrarCotizacionResult) {
            this.registrarCotizacionResult = registrarCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CotizacionServiceSoapChannel : ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CotizacionServiceSoapClient : System.ServiceModel.ClientBase<ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap>, ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap {
        
        public CotizacionServiceSoapClient() {
        }
        
        public CotizacionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CotizacionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotizacionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CotizacionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.CotizacionServiceClient.obtenerCotizacionResponse ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap.obtenerCotizacion(ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacion(request);
        }
        
        public string obtenerCotizacion(string fecha) {
            ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequest inValue = new ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequest();
            inValue.Body = new ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            ClienteSOAP.CotizacionServiceClient.obtenerCotizacionResponse retVal = ((ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap)(this)).obtenerCotizacion(inValue);
            return retVal.Body.obtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.CotizacionServiceClient.obtenerCotizacionResponse> ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap.obtenerCotizacionAsync(ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.CotizacionServiceClient.obtenerCotizacionResponse> obtenerCotizacionAsync(string fecha) {
            ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequest inValue = new ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequest();
            inValue.Body = new ClienteSOAP.CotizacionServiceClient.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            return ((ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap)(this)).obtenerCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteSOAP.CotizacionServiceClient.registrarCotizacionResponse ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap.registrarCotizacion(ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacion(request);
        }
        
        public string registrarCotizacion(string fecha, decimal monto) {
            ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequest inValue = new ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequest();
            inValue.Body = new ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            ClienteSOAP.CotizacionServiceClient.registrarCotizacionResponse retVal = ((ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap)(this)).registrarCotizacion(inValue);
            return retVal.Body.registrarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteSOAP.CotizacionServiceClient.registrarCotizacionResponse> ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap.registrarCotizacionAsync(ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteSOAP.CotizacionServiceClient.registrarCotizacionResponse> registrarCotizacionAsync(string fecha, decimal monto) {
            ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequest inValue = new ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequest();
            inValue.Body = new ClienteSOAP.CotizacionServiceClient.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            return ((ClienteSOAP.CotizacionServiceClient.CotizacionServiceSoap)(this)).registrarCotizacionAsync(inValue);
        }
    }
}
