//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OficinaTramites.SegipService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://segipip.gob.bo/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CI {
            get {
                return this.CIField;
            }
            set {
                if ((object.ReferenceEquals(this.CIField, value) != true)) {
                    this.CIField = value;
                    this.RaisePropertyChanged("CI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://segipip.gob.bo/", ConfigurationName="SegipService.ServicioSegipSoap")]
    public interface ServicioSegipSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://segipip.gob.bo/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://segipip.gob.bo/VerificarDatos", ReplyAction="*")]
        OficinaTramites.SegipService.VerificarDatosResponse VerificarDatos(OficinaTramites.SegipService.VerificarDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://segipip.gob.bo/VerificarDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<OficinaTramites.SegipService.VerificarDatosResponse> VerificarDatosAsync(OficinaTramites.SegipService.VerificarDatosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CI del espacio de nombres http://segipip.gob.bo/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://segipip.gob.bo/ObtenerDatos", ReplyAction="*")]
        OficinaTramites.SegipService.ObtenerDatosResponse ObtenerDatos(OficinaTramites.SegipService.ObtenerDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://segipip.gob.bo/ObtenerDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<OficinaTramites.SegipService.ObtenerDatosResponse> ObtenerDatosAsync(OficinaTramites.SegipService.ObtenerDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatos", Namespace="http://segipip.gob.bo/", Order=0)]
        public OficinaTramites.SegipService.VerificarDatosRequestBody Body;
        
        public VerificarDatosRequest() {
        }
        
        public VerificarDatosRequest(OficinaTramites.SegipService.VerificarDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://segipip.gob.bo/")]
    public partial class VerificarDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public VerificarDatosRequestBody() {
        }
        
        public VerificarDatosRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificarDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificarDatosResponse", Namespace="http://segipip.gob.bo/", Order=0)]
        public OficinaTramites.SegipService.VerificarDatosResponseBody Body;
        
        public VerificarDatosResponse() {
        }
        
        public VerificarDatosResponse(OficinaTramites.SegipService.VerificarDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://segipip.gob.bo/")]
    public partial class VerificarDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerificarDatosResult;
        
        public VerificarDatosResponseBody() {
        }
        
        public VerificarDatosResponseBody(bool VerificarDatosResult) {
            this.VerificarDatosResult = VerificarDatosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatos", Namespace="http://segipip.gob.bo/", Order=0)]
        public OficinaTramites.SegipService.ObtenerDatosRequestBody Body;
        
        public ObtenerDatosRequest() {
        }
        
        public ObtenerDatosRequest(OficinaTramites.SegipService.ObtenerDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://segipip.gob.bo/")]
    public partial class ObtenerDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CI;
        
        public ObtenerDatosRequestBody() {
        }
        
        public ObtenerDatosRequestBody(string CI) {
            this.CI = CI;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerDatosResponse", Namespace="http://segipip.gob.bo/", Order=0)]
        public OficinaTramites.SegipService.ObtenerDatosResponseBody Body;
        
        public ObtenerDatosResponse() {
        }
        
        public ObtenerDatosResponse(OficinaTramites.SegipService.ObtenerDatosResponseBody Body) {
            this.Body = Body;
        }

        public string Nombres { get; internal set; }
        public string PrimerApellido { get; internal set; }
        public object SegundoApellido { get; internal set; }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://segipip.gob.bo/")]
    public partial class ObtenerDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OficinaTramites.SegipService.Persona ObtenerDatosResult;
        
        public ObtenerDatosResponseBody() {
        }
        
        public ObtenerDatosResponseBody(OficinaTramites.SegipService.Persona ObtenerDatosResult) {
            this.ObtenerDatosResult = ObtenerDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioSegipSoapChannel : OficinaTramites.SegipService.ServicioSegipSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSegipSoapClient : System.ServiceModel.ClientBase<OficinaTramites.SegipService.ServicioSegipSoap>, OficinaTramites.SegipService.ServicioSegipSoap {
        
        public ServicioSegipSoapClient() {
        }
        
        public ServicioSegipSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSegipSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSegipSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSegipSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OficinaTramites.SegipService.VerificarDatosResponse OficinaTramites.SegipService.ServicioSegipSoap.VerificarDatos(OficinaTramites.SegipService.VerificarDatosRequest request) {
            return base.Channel.VerificarDatos(request);
        }
        
        public bool VerificarDatos(string CI) {
            OficinaTramites.SegipService.VerificarDatosRequest inValue = new OficinaTramites.SegipService.VerificarDatosRequest();
            inValue.Body = new OficinaTramites.SegipService.VerificarDatosRequestBody();
            inValue.Body.CI = CI;
            OficinaTramites.SegipService.VerificarDatosResponse retVal = ((OficinaTramites.SegipService.ServicioSegipSoap)(this)).VerificarDatos(inValue);
            return retVal.Body.VerificarDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OficinaTramites.SegipService.VerificarDatosResponse> OficinaTramites.SegipService.ServicioSegipSoap.VerificarDatosAsync(OficinaTramites.SegipService.VerificarDatosRequest request) {
            return base.Channel.VerificarDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OficinaTramites.SegipService.VerificarDatosResponse> VerificarDatosAsync(string CI) {
            OficinaTramites.SegipService.VerificarDatosRequest inValue = new OficinaTramites.SegipService.VerificarDatosRequest();
            inValue.Body = new OficinaTramites.SegipService.VerificarDatosRequestBody();
            inValue.Body.CI = CI;
            return ((OficinaTramites.SegipService.ServicioSegipSoap)(this)).VerificarDatosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OficinaTramites.SegipService.ObtenerDatosResponse OficinaTramites.SegipService.ServicioSegipSoap.ObtenerDatos(OficinaTramites.SegipService.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatos(request);
        }
        
        public OficinaTramites.SegipService.Persona ObtenerDatos(string CI) {
            OficinaTramites.SegipService.ObtenerDatosRequest inValue = new OficinaTramites.SegipService.ObtenerDatosRequest();
            inValue.Body = new OficinaTramites.SegipService.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            OficinaTramites.SegipService.ObtenerDatosResponse retVal = ((OficinaTramites.SegipService.ServicioSegipSoap)(this)).ObtenerDatos(inValue);
            return retVal.Body.ObtenerDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OficinaTramites.SegipService.ObtenerDatosResponse> OficinaTramites.SegipService.ServicioSegipSoap.ObtenerDatosAsync(OficinaTramites.SegipService.ObtenerDatosRequest request) {
            return base.Channel.ObtenerDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OficinaTramites.SegipService.ObtenerDatosResponse> ObtenerDatosAsync(string CI) {
            OficinaTramites.SegipService.ObtenerDatosRequest inValue = new OficinaTramites.SegipService.ObtenerDatosRequest();
            inValue.Body = new OficinaTramites.SegipService.ObtenerDatosRequestBody();
            inValue.Body.CI = CI;
            return ((OficinaTramites.SegipService.ServicioSegipSoap)(this)).ObtenerDatosAsync(inValue);
        }
    }
}
